import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import ReduxProvider from "./redux/ReduxProvider";
import ThemeManager from "./Components/ThemeManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          <ThemeManager />
          <Header />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
